In [ ]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)

In [ ]:
df = pd.read_csv('drive/MyDrive/violencia_2009_2021.csv')

<ipython-input-2-11b5eddc39a3>:1: DtypeWarning: Columns (14,16,20,42,48,52) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('drive/MyDrive/violencia_2009_2021.csv')


In [ ]:
df.shape

(1700365, 100)

# Tratamentos a realizar
- Transformar nulos em nulos
- Transformar numéricos em numéricos
- Alterar os resultados das colunas para os do dicionário

In [ ]:
col_conjunto = ['DEF_TRANS', 'OUT_VEZES', 'LES_AUTOP', 'VIOL_FISIC', 'VIOL_PSICO', 'VIOL_TORT', 'VIOL_SEXU',
                'VIOL_TRAF', 'VIOL_FINAN', 'VIOL_LEGAL', 'VIOL_NEGLI', 'VIOL_INFAN', 'AG_FORCA', 'AG_ENFOR',
                'AG_OBJETO', 'AG_CORTE', 'AG_QUENTE', 'AG_ENVEN', 'AG_FOGO', 'AG_AMEACA', 'SEX_ESTUPR',
                'SEX_PUDOR', 'SEX_EXPLO', 'SEX_PORNO', 'REL_PAI', 'REL_PAD', 'REL_MAD', 'REL_CONJ', 'REL_EXCON',
                'REL_NAMO', 'REL_EXNAM', 'REL_FILHO', 'REL_DESCO', 'REL_IRMAO', 'REL_CUIDA', 'REL_CONHEC',
                'REL_PATRAO', 'REL_INST', 'REL_MAE', 'REL_POL', 'AUTOR_ALCO', 'ENC_TUTELA',
                'ENC_VARA', 'ENC_ABRIGO', 'ENC_SENTIN', 'ENC_DEAM', 'ENC_DPCA', 'ENC_DELEG', 'ENC_MPU',
                'ENC_MULHER', 'ENC_CREAS', 'ENC_IML', 'REL_TRAB', 'REDE_SAU', 'ASSIST_SOC', 'REDE_EDUCA',
                'ATEND_MULH', 'DIR_HUMAN', 'MPU', 'DELEG_MULH', 'DELEG', 'DEFEN_PUBL', 'ENC_SAUDE', 'SEX_ASSEDI']

col_data_hora = ['DT_ENCERRA', 'DT_OBITO', 'HORA_OCOR', 'DT_OCOR', 'DT_NOTIFIC']

col_outros_tratamentos = ['AUTOR_SEXO', 'NUM_ENVOLV', 'LOCAL_OCOR', 'ID_MN_OCOR', 'ANO_NASC',
                          'SG_UF_OCOR', 'ID_OCUPA_N', 'ID_PAIS', 'ID_MN_RESI', 'SG_UF', 'CS_ESCOL_N', 'CS_RACA',
                          'CS_GESTANT', 'ID_MUNICIP', 'SG_UF_NOT', 'NU_ANO', 'ORIENT_SEX', 'IDENT_GEN', 'VIOL_MOTIV',
                          'CICL_VID', 'SIT_CONJUG', 'ID_UNIDADE']

col_fora_dict = ['CLASSI_FIN', 'EVOLUCAO', 'REL_SEXUAL', 'LESAO_CORP', 'LESAO_NAT', 'LESAO_ESPE']

col_drop = ['TP_NOT']

col_filtragem = ['CS_SEXO', 'NDUPLIC']

listas_tratamentos = ['col_conjunto', 'col_data_hora', 'col_outros_tratamentos', 'col_fora_dict', 'col_drop',
                      'col_filtragem']


## Transformando nulos em nulos

In [ ]:
df.replace('', None, inplace=True)

In [ ]:
df.isna().mean()*100

TP_NOT          0.000000
DT_NOTIFIC      0.000000
NU_ANO          0.001411
SG_UF_NOT       0.000000
ID_MUNICIP      0.000000
ID_UNIDADE      0.180020
DT_OCOR         0.817001
ANO_NASC        2.581563
CS_SEXO         0.000000
CS_GESTANT      0.000000
CS_RACA         1.284959
CS_ESCOL_N      5.774937
SG_UF           0.016055
ID_MN_RESI      0.016055
ID_PAIS         0.271765
NDUPLIC       100.000000
ID_OCUPA_N     54.280581
SIT_CONJUG      2.689070
DEF_TRANS       1.873362
SG_UF_OCOR      2.814690
ID_MN_OCOR      3.859348
HORA_OCOR      43.547356
LOCAL_OCOR      1.475036
OUT_VEZES       2.135659
LES_AUTOP       2.662134
VIOL_FISIC      1.908708
VIOL_PSICO      3.632808
VIOL_TORT       4.623301
VIOL_SEXU       4.231268
VIOL_TRAF       4.707460
VIOL_FINAN      4.660470
VIOL_LEGAL      4.720045
VIOL_NEGLI      4.216742
VIOL_INFAN      4.732866
AG_FORCA        3.252831
AG_ENFOR        5.376081
AG_OBJETO       5.398900
AG_CORTE        5.228407
AG_QUENTE       5.474236
AG_ENVEN        5.546162


## Transformando numéricos em numéricos

In [ ]:
listas_tratamentos

['col_conjunto',
 'col_data_hora',
 'col_outros_tratamentos',
 'col_fora_dict',
 'col_drop',
 'col_filtragem']

In [ ]:
print(len(df.columns))
df[col_conjunto + col_outros_tratamentos + col_fora_dict +
     col_drop + col_filtragem ] =  df[col_conjunto + col_outros_tratamentos +
                                        col_fora_dict + col_drop + col_filtragem
                                        ].apply(pd.to_numeric, errors='coerce')

100


In [ ]:
len(df.columns)

100

### Dropar colunas
listas: 'col_fora_dict', 'col_drop', 'col_filtragem',

In [ ]:
df = df.drop(col_fora_dict + col_drop + col_filtragem, axis=1)

In [ ]:
len(df.columns)

91

## Alterando resposta das colunas
- Conjunto de colunas com
  - 1: sim
  - 2: nao
  - 8: não aplicavel
  - 9: ignorado

- Data e hora

- Outros tratamentos

- Drop

### Conjunto de colunas com mesmo tratamento
lista: col_conjunto




In [ ]:
mapeamento = {1.0: 'Sim',
              2.0: 'Não',
              8.0: 'Não aplicável',
              9.0: 'Ignorado'}

for coluna in col_conjunto:
    df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

for coluna in col_conjunto:
    print(f'{coluna}\n{df[coluna].unique()}\n\n')

DEF_TRANS
['Não' 'Ignorado' 'Sim' nan 'Não aplicável']


OUT_VEZES
['Não' 'Ignorado' 'Sim' nan]


LES_AUTOP
['Não' 'Ignorado' nan 'Sim']


VIOL_FISIC
['Sim' 'Não' nan 'Ignorado']


VIOL_PSICO
['Não' 'Sim' 'Ignorado' nan]


VIOL_TORT
['Não' 'Sim' 'Ignorado' nan]


VIOL_SEXU
['Não' 'Sim' 'Ignorado' nan]


VIOL_TRAF
['Não' 'Ignorado' nan 'Sim']


VIOL_FINAN
['Não' 'Ignorado' nan 'Sim']


VIOL_LEGAL
['Não' 'Ignorado' nan 'Sim']


VIOL_NEGLI
['Sim' 'Não' 'Ignorado' nan]


VIOL_INFAN
['Não' 'Ignorado' nan 'Sim']


AG_FORCA
['Sim' 'Não' 'Ignorado' nan]


AG_ENFOR
['Não' 'Ignorado' nan 'Sim']


AG_OBJETO
['Não' 'Ignorado' 'Sim' nan]


AG_CORTE
['Não' 'Sim' 'Ignorado' nan]


AG_QUENTE
['Não' 'Ignorado' 'Sim' nan]


AG_ENVEN
['Não' 'Ignorado' nan 'Sim']


AG_FOGO
['Não' 'Ignorado' 'Sim' nan]


AG_AMEACA
['Não' 'Ignorado' 'Sim' nan]


SEX_ESTUPR
['Não aplicável' 'Sim' nan 'Não' 'Ignorado']


SEX_PUDOR
['Não aplicável' 'Não' 'Sim' nan 'Ignorado']


SEX_EXPLO
['Não aplicável' 'Sim' 'Não' nan 'Ignor

### Data e hora

In [ ]:
for coluna in col_data_hora:
    print(f'{coluna}\n{df[coluna].unique()}\n\n')

DT_ENCERRA
[20090512. 20091201. 20090122. ... 20220813. 20220814. 20220821.]


DT_OBITO
[      nan 20090308. 20090409. ... 20140617. 20141225. 20150402.]


HORA_OCOR
[nan '09:00' '22:00' ... '04:48' '00000' '05:36']


DT_OCOR
[20090512. 20091201. 20090122. ... 20020824. 19970812. 20071207.]


DT_NOTIFIC
['2009-05-12' '2009-12-01' '2009-01-22' ... '2021-12-18' '2021-12-19'
 '2021-12-20']




In [ ]:
df[['DT_ENCERRA', 'DT_OBITO', 'DT_OCOR']] = df[['DT_ENCERRA', 'DT_OBITO', 'DT_OCOR']].fillna('00010101').astype(int).astype(str)

In [ ]:
# Verifique se os valores não atendem ao padrão usando regex e negando a condição
padrao = r'^\d{4}(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])$'
valores_nao_corretos = ~df['DT_ENCERRA'].str.match(padrao, na=False)

# Crie um novo DataFrame com os valores que não atendem ao padrão
df_nao_corretos = df[valores_nao_corretos]

# Imprima os resultados, se desejar
print("Valores que não atendem ao padrão:")
print(df_nao_corretos['DT_ENCERRA'].head())

Valores que não atendem ao padrão:
22      10101
476     10101
796     10101
1388    10101
2250    10101
Name: DT_ENCERRA, dtype: object


In [ ]:
df.loc[df.DT_ENCERRA == '10101','DT_ENCERRA'] = '00010101'
df.loc[df.DT_OBITO == '10101','DT_OBITO'] = '00010101'
df.loc[df.DT_OCOR == '10101','DT_OCOR'] = '00010101'

In [ ]:
df[['DT_ENCERRA', 'DT_OBITO', 'DT_OCOR']] = df[['DT_ENCERRA', 'DT_OBITO',
                                                    'DT_OCOR']].replace('00010101', np.nan)

df['DT_ENCERRA'] = pd.to_datetime(df['DT_ENCERRA'], format='%Y%m%d').dt.strftime('%d/%m/%Y')
df['DT_OBITO'] = pd.to_datetime(df['DT_OBITO'], format='%Y%m%d').dt.strftime('%d/%m/%Y')
df['DT_OCOR'] = pd.to_datetime(df['DT_OCOR'], format='%Y%m%d').dt.strftime('%d/%m/%Y')

In [ ]:
df['DT_NOTIFIC'] = pd.to_datetime(df['DT_NOTIFIC'], format='%Y-%m-%d').dt.strftime('%d/%m/%Y')

In [ ]:
df.loc[df.HORA_OCOR == '00000'] = np.nan
df['HORA_OCOR'] = pd.to_datetime(df['HORA_OCOR'], format='%H:%M').dt.strftime('%H:%M')

### Outros tratamentos
Aqui tem que tratar coluna por coluna

lista: col_outros_tratamentos

#### AUTOR_SEXO

In [ ]:
df.AUTOR_SEXO.unique()

array([ 2.,  1.,  9., nan,  3.])

In [ ]:
mapeamento = {1.0: 'Masculino',
              2.0: 'Feminino',
              8.0: 'Ambos',
              9.0: 'Ignorado'}

coluna = 'AUTOR_SEXO'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array(['Feminino', 'Masculino', 'Ignorado', nan], dtype=object)

#### NUM_ENVOLV


In [ ]:
df.NUM_ENVOLV.unique()

array([ 1.,  9.,  2., nan,  3.])

In [ ]:
mapeamento = {1.0: 'Um',
              2.0: 'Dois ou mais',
              9.0: 'Ignorado'}

coluna = 'NUM_ENVOLV'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array(['Um', 'Ignorado', 'Dois ou mais', nan], dtype=object)

#### LOCAL_OCOR

In [ ]:
df.LOCAL_OCOR.unique()

array([ 1.,  7., 99.,  9.,  6., nan,  3.,  2.,  5.,  4.,  8.])

In [ ]:
mapeamento = {1.0: 'Residência',
              2.0: 'Habitação_coletiva',
              3.0: 'Escola',
              4.0: 'Local_prática_esportiva',
              5.0: 'Bar_ou_similar',
              6.0: 'Via_publica',
              7.0: 'Comércio_serviços',
              8.0: 'Industrias_construção',
              9.0: 'Outros',
              99.0: 'Ignorado'}

coluna = 'LOCAL_OCOR'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array(['Residência', 'Comércio_serviços', 'Ignorado', 'Outros',
       'Via_publica', nan, 'Escola', 'Habitação_coletiva',
       'Bar_ou_similar', 'Local_prática_esportiva',
       'Industrias_construção'], dtype=object)

#### CS_ESCOL_N

In [ ]:
df.CS_ESCOL_N.unique()

array([10.,  6.,  9.,  4.,  1.,  3., nan,  8.,  2.,  5.,  7.,  0.])

In [ ]:
mapeamento = {0.0: 'Analfabeto',
              1.0: 'Fundamental I incompleto',
              2.0: 'Fundamental I completo',
              3.0: 'Fundamental II incompleto',
              4.0: 'Fundamental II completo',
              5.0: 'Ensino médio incompleto',
              6.0: 'Ensino médio completo',
              7.0: 'Educação superior incompleta',
              8.0: 'Educação superior completa',
              9.0: 'Ignorado',
              10.0: 'Não aplicável'}

coluna = 'CS_ESCOL_N'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array(['Não aplicável', 'Ensino médio completo', 'Ignorado',
       'Fundamental II completo', 'Fundamental I incompleto',
       'Fundamental II incompleto', nan, 'Educação superior completa',
       'Fundamental I completo', 'Ensino médio incompleto',
       'Educação superior incompleta', 'Analfabeto'], dtype=object)

#### CS_RACA

In [ ]:
df.CS_RACA.unique()

array([ 1.,  2.,  9.,  4.,  5., nan,  3.])

In [ ]:
mapeamento = {1.0: 'Branca',
              2.0: 'Preta',
              3.0: 'Amarela',
              4.0: 'Parda',
              5.0: 'Indigena'}

coluna = 'CS_RACA'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array(['Branca', 'Preta', nan, 'Parda', 'Indigena', 'Amarela'],
      dtype=object)

#### CS_GESTANT

In [ ]:
df.CS_GESTANT.unique()

array([ 6.,  5.,  9.,  4.,  3.,  1.,  2., nan,  8.])

In [ ]:
mapeamento = {1.0: '1º Trimestre',
              2.0: '2º Trimestre',
              3.0: '3º Trimestre',
              4.0: 'Idade gestacional ignorada',
              5.0: 'Não',
              6.0: 'Não se aplica',
              9.0: 'Ignorado' }

coluna = 'CS_GESTANT'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array(['Não se aplica', 'Não', 'Ignorado', 'Idade gestacional ignorada',
       '3º Trimestre', '1º Trimestre', '2º Trimestre', nan], dtype=object)

#### ORIENT_SEX

In [ ]:
df.ORIENT_SEX.unique()

array([nan,  9.,  1.,  8.,  2.,  3.])

In [ ]:
mapeamento = {1.0: 'Heterossexual',
              2.0: 'Homossexual',
              3.0: 'Bissexual',
              8.0: 'Não se aplica',
              9.0: 'Ignorado'}

coluna = 'ORIENT_SEX'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array([nan, 'Ignorado', 'Heterossexual', 'Não se aplica', 'Homossexual',
       'Bissexual'], dtype=object)

#### IDENT_GEN

In [ ]:
df.IDENT_GEN.unique()

array([nan,  9.,  8.,  2.,  3.,  1.])

In [ ]:
mapeamento = {1.0: 'Travesti',
              2.0: 'Transexual Mulher',
              3.0: 'Transexual Homem',
              4.0: 'Não se aplica',
              5.0: 'Ignorado'}

coluna = 'IDENT_GEN'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array([nan, 'Transexual Mulher', 'Transexual Homem', 'Travesti'],
      dtype=object)

#### VIOL_MOTIV

In [ ]:
df.VIOL_MOTIV.unique()

array([nan,  9., 88., 99.,  6.,  7.,  8.,  1.,  2.,  4.,  3.,  5.])

In [ ]:
mapeamento = {1.0: 'Sexismo',
              2.0: 'Homofobia/Lesbofobia/Bifobia/Transfobia',
              3.0: 'Racismo',
              4.0: 'Intolerância religiosa',
              5.0: 'Xenofobia',
              6.0: 'Conflito geracional',
              7.0: 'Situação de rua',
              8.0: 'Deficiência',
              9.0: 'Outros',
              88.0: 'Não se aplica',
              99.0: 'Ignorado'}

coluna = 'VIOL_MOTIV'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array([nan, 'Outros', 'Não se aplica', 'Ignorado', 'Conflito geracional',
       'Situação de rua', 'Deficiência', 'Sexismo',
       'Homofobia/Lesbofobia/Bifobia/Transfobia',
       'Intolerância religiosa', 'Racismo', 'Xenofobia'], dtype=object)

#### CICL_VID

In [ ]:
df.CICL_VID.unique()

array([nan,  9.,  4.,  3.,  2.,  1.,  5.])

In [ ]:
mapeamento = {1.0: 'Criança',
              2.0: 'Adolescente',
              3.0: 'Jovem',
              4.0: 'Pessoa adulta',
              5.0: 'Pessoa idosa',
              9.0: 'Ignorado'}

coluna = 'CICL_VID'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array([nan, 'Ignorado', 'Pessoa adulta', 'Jovem', 'Adolescente',
       'Criança', 'Pessoa idosa'], dtype=object)

#### SIT_CONJUG

In [ ]:
df.SIT_CONJUG.unique()

array([ 8.,  2.,  9.,  1., nan,  4.,  3.])

In [ ]:
mapeamento = {1.0: 'Solteiro',
              2.0: 'Casado/ União consensual',
              3.0: 'Viúvo',
              4.0: 'Separado',
              8.0: 'Não aplicável',
              9.0: 'Ignorado'}

coluna = 'SIT_CONJUG'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array(['Não aplicável', 'Casado/ União consensual', 'Ignorado',
       'Solteiro', nan, 'Separado', 'Viúvo'], dtype=object)

#### NU_ANO e ANO_NASC


In [ ]:
df.NU_ANO.unique()

array([2009., 2010., 2011., 2012., 2013.,   nan, 2014., 2015., 2016.,
       2017., 2018., 2019., 2020., 2021.])

In [ ]:
df.ANO_NASC.unique()

array([2004., 1980.,   nan, 2009., 1988., 1976., 1969., 1942., 1950.,
       1982., 1983., 1963., 1967., 1971., 2005., 1993., 2001., 2008.,
       1975., 2002., 1966., 1917., 1986., 1973., 1994., 1978., 1992.,
       1984., 1989., 1991., 1965., 1979., 1995., 1958., 1999., 1981.,
       1946., 1970., 1968., 1972., 1964., 1977., 1990., 1987., 1985.,
       1945., 1998., 1996., 1960., 1934., 1941., 1974., 2003., 2006.,
       1940., 1927., 1957., 2007., 1997., 1961., 1944., 1956., 1962.,
       1951., 1959., 1933., 1939., 1953., 1937., 1929., 1915., 1943.,
       2000., 1925., 1923., 1955., 1948., 1949., 1947., 1952., 1935.,
       1936., 1931., 1938., 1912., 1930., 1954., 1916., 1932., 1906.,
       1922., 1921., 1914., 1926., 1924., 1910., 1928., 1919., 1907.,
       1920., 1908., 1918., 1911., 1913., 2010., 1901., 2011., 1909.,
       1904., 1900., 1905., 2012., 1902., 2013., 1903., 2014., 2015.,
       2016., 2017., 2018., 2019., 2020., 2021.])

In [ ]:
df['IDADE'] = df['NU_ANO'] - df['ANO_NASC']

In [ ]:
df.IDADE.unique()

array([  5.,  29.,  nan,   0.,  21.,  33.,  40.,  67.,  59.,  27.,  26.,
        46.,  42.,  38.,   4.,  16.,   8.,   1.,  34.,   7.,  43.,  92.,
        23.,  36.,  15.,  31.,  17.,  25.,  20.,  18.,  44.,  30.,  14.,
        51.,  10.,  28.,  63.,  39.,  41.,  37.,  45.,  32.,  19.,  22.,
        24.,  64.,  11.,  13.,  49.,  75.,  68.,  35.,   6.,   3.,  69.,
        82.,  52.,   2.,  12.,  48.,  65.,  53.,  47.,  58.,  50.,  76.,
        70.,  56.,  72.,  80.,  94.,  66.,   9.,  84.,  86.,  54.,  61.,
        60.,  62.,  57.,  74.,  73.,  78.,  71.,  97.,  79.,  55.,  93.,
        77., 103.,  87.,  88.,  95.,  83.,  85.,  99.,  81.,  90., 102.,
        89., 101.,  91.,  98.,  96., 100., 109., 105., 107., 111., 106.,
       110., 104., 108., 112., 113., 114., 115., 116., 117., 118., 119.,
       121.])

#### SG_UF_OCOR
Extraído do IBGE, de acordo com dicionário de dados


In [ ]:
df_uf = df_municipio.groupby('Nome_UF')['UF'].min().reset_index()
df_uf.set_index("UF", inplace=True)

In [ ]:
df_uf.head()

Nome_UF
UF          
12      Acre
27   Alagoas
16     Amapá
13  Amazonas
29     Bahia

In [ ]:
df.SG_UF_OCOR.unique()

array([41., 29., 52., 13., 26., nan, 23., 25., 42., 21., 43., 32., 50.,
       35., 14., 22., 33., 12., 15., 11., 53., 31., 17., 24., 51., 28.,
       27., 16.])

In [ ]:
mapeamento = df_uf["Nome_UF"].to_dict()

coluna = 'SG_UF_OCOR'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array(['Paraná', 'Bahia', 'Goiás', 'Amazonas', 'Pernambuco', nan, 'Ceará',
       'Paraíba', 'Santa Catarina', 'Maranhão', 'Rio Grande do Sul',
       'Espírito Santo', 'Mato Grosso do Sul', 'São Paulo', 'Roraima',
       'Piauí', 'Rio de Janeiro', 'Acre', 'Pará', 'Rondônia',
       'Distrito Federal', 'Minas Gerais', 'Tocantins',
       'Rio Grande do Norte', 'Mato Grosso', 'Sergipe', 'Alagoas',
       'Amapá'], dtype=object)

#### SG_UF

In [ ]:
df.SG_UF.unique()

array([41., 29., 52., 13., 26., 23., 25., 42., 35., 21., 43., 50., 27.,
       14., 22., nan, 31., 12., 33., 15., 11., 53., 32., 24., 51., 28.,
       17., 16.])

In [ ]:
mapeamento = df_uf["Nome_UF"].to_dict()

coluna = 'SG_UF'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array(['Paraná', 'Bahia', 'Goiás', 'Amazonas', 'Pernambuco', 'Ceará',
       'Paraíba', 'Santa Catarina', 'São Paulo', 'Maranhão',
       'Rio Grande do Sul', 'Mato Grosso do Sul', 'Alagoas', 'Roraima',
       'Piauí', nan, 'Minas Gerais', 'Acre', 'Rio de Janeiro', 'Pará',
       'Rondônia', 'Distrito Federal', 'Espírito Santo',
       'Rio Grande do Norte', 'Mato Grosso', 'Sergipe', 'Tocantins',
       'Amapá'], dtype=object)

#### SG_UF_NOT

In [ ]:
df.SG_UF_NOT.unique()

array([41., 29., 52., 13., 26., 23., 25., 42., 21., 43., 50., 27., 14.,
       22., 35., 31., 12., 33., 15., 53., 32., 24., 51., 11., 28., 17.,
       16., nan])

In [ ]:
mapeamento = df_uf["Nome_UF"].to_dict()

coluna = 'SG_UF_NOT'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array(['Paraná', 'Bahia', 'Goiás', 'Amazonas', 'Pernambuco', 'Ceará',
       'Paraíba', 'Santa Catarina', 'Maranhão', 'Rio Grande do Sul',
       'Mato Grosso do Sul', 'Alagoas', 'Roraima', 'Piauí', 'São Paulo',
       'Minas Gerais', 'Acre', 'Rio de Janeiro', 'Pará',
       'Distrito Federal', 'Espírito Santo', 'Rio Grande do Norte',
       'Mato Grosso', 'Rondônia', 'Sergipe', 'Tocantins', 'Amapá', nan],
      dtype=object)

#### ID_OCUPA_N
Equivalencia vinda do CBO (Classificação Brasileira de Ocupações)

In [ ]:
df_cbo = pd.read_csv('CBO2002 - Ocupacao.csv', encoding='latin-1', sep=';')

In [ ]:
df_cbo.head()

CODIGO                          TITULO
0   10105  Oficial general da aeronáutica
1   10110     Oficial general do exército
2   10115      Oficial general da marinha
3   10205          Oficial da aeronáutica
4   10210             Oficial do exército

In [ ]:
df.ID_OCUPA_N.unique()

array([    nan, 524205., 999991., ..., 214745., 762125., 722105.])

In [ ]:
df_cbo.set_index("CODIGO", inplace=True)
mapeamento = df_cbo["TITULO"].to_dict()

coluna = 'ID_OCUPA_N'

# Substituir valores diferentes pelos que estão no mapeamento e o restante por NaN
df[coluna] = df[coluna].map(lambda x: mapeamento.get(x, np.nan))

df[coluna].unique()

array([nan, 'Feirante', 'Caseiro (agricultura)', ...,
       'Tecnólogo em petróleo e gás', 'Rachador de couros e peles',
       'Forjador'], dtype=object)

In [ ]:
df.to_csv('drive/MyDrive/violencia_2009_2021_tratado.csv', index = False)